### ISSUE TITLE
[FEATURE] fetching process 모듈 분리

### ISSUE THREAD

**Issue by oxdjww** [gazok/ploio_server#5]
## 이슈 내용

- fetching process 메서드를 통해 비동기로 http request packet을 보내려고 했으나, wireshark를 통한 패킷 캡쳐를 해보았을 때 포착되지 않음

## 시도

[commit](https://github.com/gazok/ploio_server/commit/f2002d35e96534b9f40352b17cba1e433a6b42a1)

- main.py에 메서드를 옮기고, 로컬에서 서버를 실행시켜 보았으나 `INFO: Waiting for application startup.`라는 메시지와 함께 stuck

## 체크리스트

- [ ] 패킷이 캡쳐되는지 
- [ ] 서버가 죽지 않고 잘 살아있는지
- [ ] 계속 서버를 돌렸을 때, queue buffer에 저장된 data가 비워지는지

**Comment by limjung99** [comment]
service.py 의 서비스 레이어 인스턴스를 살펴보니 async 함수 내부에 await 키워드가 없네요. 그게 문제일지도 모릅니다.

**Comment by oxdjww** [comment]
> service.py 의 서비스 레이어 인스턴스를 살펴보니 async 함수 내부에 await 키워드가 없네요. 그게 문제일지도 모릅니다.

22행, 36행 말고 다른 곳 말씀하시는 걸까요?

**Comment by oxdjww** [comment]
버그가 아니라 기능이였네요
![image](https://github.com/gazok/ploio_server/assets/102507306/1d491161-851d-496d-8b6f-41b0cb7872ce)
```
async def send_http_get_request(self):
        response = await requests.get(f"{self.agent_url}")
        return response.content
```

`response`가 안 오는 상황에서 `await` 키워드 때문에 동기로 처리되어 flow가 계속 저 함수 내에서 멈춰있었습니다.

현재 상황에서 `worker node`로 `req`보냈을 때 `reply`가 오지 않는 것은 당연하니.. 버그가 아니라 기능이였네요..

[Ref](https://kdw9502.tistory.com/6)
